### ISSUE TITLE
Logggers confused by "." or ":" in LoggerConfiguration name (using EndpointWeb)

### ISSUE THREAD

**Issue by dwilliss** [SteeltoeOSS/steeltoe-site#15]
We have a custom DynamicLoggerProvider in which we add custom log configurations based on our configuration.  This is a multi-tenant application and we allow you to set log level per-tenant using the GroupName:Whatever configurations.

![image](https://user-images.githubusercontent.com/1755696/47034947-5dff7380-d13e-11e8-9e0f-b8c066afb613.png)

In a .NET Core app, this works just fine.  We can adjust the log levels for the different groups (this example only has one)

But in a legacy (non-core) ashx application using the EndpointWeb dll, this doesn't work.

![image](https://user-images.githubusercontent.com/1755696/47035156-e8e06e00-d13e-11e8-9ebf-6e1a668dc5b5.png)

The Options call gets a 404 error.  It works for all the other logger configurations, just not the ones with ":" in them.

I tried changing the ":" to a "." thinking maybe something was trying to interpret that as a port number, but that didn't work either.  Changing it to a "-" worked.

**Comment by TimHess** [comment]
Finally got around to adding a note about this and general how-to with the loggers actuator, thanks for your feedback!
