### ISSUE TITLE
Ambiguous ServiceDiscovery doc in "3.2.5 Configuring Metadata"?

### ISSUE THREAD

**Issue by labarilem** [SteeltoeOSS/steeltoe-site#37]
By reading the paragraph _3.2.5 Configuring Metadata_ in the ServiceDiscovery documentation, it looked like this one would be the correct way to configure tags for a Consul service:

```
"tags": "key1=value1,key2=value2"
```

Instead, I found this is the correct way:

```
"tags": ["key1=value1", "key2=value2"]
```

Is it just me or that paragraph looks ambiguous?

**Comment by TimHess** [comment]
You're right, we can spell this out better... if you look at the source code (a step further than you should need to go when reading docs), Tags is typed `IList<string>`. We're relying on .NET Configuration to do the mapping from app configuration to `ConsulDiscoveryOptions`, which won't be successful when a string is provided. 

I'll get an update to the docs and add a unit test that defines more than one tag.
